# Generated by Django 5.2 on 2025-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="response",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="response",
            new_name="content",
        ),
    ]
