# Generated by Django 5.2 on 2025-05-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='entity/')),
                ('type', models.CharField(choices=[('electricity', 'Électricité'), ('water', 'Eau'), ('internet', 'Internet')], max_length=255)),
                ('on', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('on', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='house.entity')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Maison', 'Maison'), ('Entreprise', 'Entreprise'), ('Ecole', 'Ecole'), ('Mairie', 'Mairie'), ('Gare', 'Gare')], default='Maison', max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='house/')),
                ('address', models.CharField(max_length=255)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='house.city')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='house.house'),
        ),
    ]
