# Generated by Django 5.2 on 2025-05-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='city',
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='coordX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='coordY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='house/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
