# Generated by Django 5.2 on 2025-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_alter_entity_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="on",
            field=models.BooleanField(default=True),
        ),
    ]
