# Generated by Django 5.2 on 2025-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_entity_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="adress",
            new_name="address",
        ),
        migrations.AddField(
            model_name="house",
            name="name",
            field=models.CharField(default="Maison Test", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="type",
            field=models.CharField(
                choices=[
                    ("Maison", "Maison"),
                    ("Entreprise", "Entreprise"),
                    ("Ecole", "Ecole"),
                    ("Mairie", "Mairie"),
                    ("Gare", "Gare"),
                ],
                default="Maison",
                max_length=20,
            ),
        ),
    ]
