# Generated by Django 5.2 on 2025-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_rename_adress_house_address_house_name_house_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="name",
            field=models.CharField(default="nom", max_length=128),
            preserve_default=False,
        ),
    ]
