# Generated by Django 5.2 on 2025-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_entity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                choices=[
                    ("electricity", "Électricité"),
                    ("water", "Eau"),
                    ("internet", "Internet"),
                ],
                max_length=255,
            ),
        ),
    ]
