# Generated by Django 5.2 on 2025-05-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0007_entityhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entityhistory",
            old_name="active",
            new_name="on",
        ),
    ]
