<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-04 14:33
=======
# Generated by Django 5.2 on 2025-05-04 14:02
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('house', '0008_rename_active_entityhistory_on'),
=======
        ("house", "0008_rename_active_entityhistory_on"),
>>>>>>> main
    ]

    operations = [
        migrations.RenameField(
<<<<<<< HEAD
            model_name='entity',
            old_name='on',
            new_name='active',
        ),
        migrations.AddField(
            model_name='entity',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='y',
=======
            model_name="entity",
            old_name="on",
            new_name="active",
        ),
        migrations.AddField(
            model_name="entity",
            name="x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entity",
            name="y",
>>>>>>> main
            field=models.IntegerField(default=0),
        ),
    ]
