# Generated by Django 5.2 on 2025-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_rename_active_entityhistory_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='on',
            new_name='active',
        ),
        migrations.AddField(
            model_name='entity',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
