# Generated by Django 5.2 on 2025-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_rename_on_entity_active_entity_x_entity_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='entity/'),
        ),
    ]
