# Generated by Django 5.2 on 2025-05-04 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0009_rename_on_entity_active_entity_x_entity_y"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("photo", models.ImageField(upload_to="news/")),
                ("content", models.CharField(max_length=256)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="house.house",
                    ),
                ),
            ],
        ),
    ]
