# Generated by Django 5.2 on 2025-05-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0010_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="city",
        ),
        migrations.AlterField(
            model_name="house",
            name="coordX",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="coordY",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="house",
            name="type",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(upload_to="newsHouse/"),
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("resolved", models.BooleanField(default=False)),
                ("response", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident",
                        to="house.entity",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="City",
        ),
    ]
