# Generated by Django 5.2 on 2025-05-04 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0011_remove_house_city_alter_house_coordx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="incident",
            name="type",
            field=models.CharField(
                choices=[
                    ("technique", "Technique"),
                    ("budgétaire", "Budgétaire"),
                    ("internet", "Internet"),
                    ("pièce", "Pièce"),
                ],
                default="technique",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entity",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="entity/"),
        ),
    ]
