# Generated by Django 5.2 on 2025-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0012_incident_date_incident_type_alter_entity_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electricity", "Électricité"),
                    ("water", "Eau"),
                    ("internet", "Internet"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
