# Generated by Django 5.2 on 2025-05-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux_type', models.CharField(choices=[('electricity', 'Électricité'), ('water', 'Eau'), ('internet', 'Internet')], max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('display_value', models.CharField(default='0', max_length=50)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_stats', to='house.entity')),
            ],
        ),
        migrations.CreateModel(
            name='FluxStatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux_type', models.CharField(choices=[('electricity', 'Électricité'), ('water', 'Eau'), ('internet', 'Internet')], max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_history', to='house.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('electricity', 'Électricité'), ('water', 'Eau'), ('internet', 'Internet')], max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='house.entity')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='house.entity')),
            ],
        ),
    ]
