# Generated by Django 5.2 on 2025-05-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0007_entityhistory"),
        ("log", "0003_alter_fluxstat_flux_type_alter_link_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FluxStatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flux_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Électricité"),
                            ("water", "Eau"),
                            ("internet", "Internet"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flux_history",
                        to="house.entity",
                    ),
                ),
            ],
        ),
    ]
