# Generated by Django 5.2 on 2025-05-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0004_fluxstathistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxstat",
            name="display_value",
            field=models.CharField(default="0", max_length=50),
        ),
    ]
