# Generated by Django 5.2 on 2025-04-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="acces",
            field=models.BooleanField(default=False),
        ),
    ]
