# Generated by Django 5.2 on 2025-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_acces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("complexe", "Complexe"),
                    ("admin", "Admin"),
                ],
                default="utilisateur",
                max_length=20,
            ),
        ),
    ]
