# Generated by Django 5.2 on 2025-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_profile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="acces",
            new_name="access",
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("complexe", "Complexe"),
                    ("admin", "Admin"),
                ],
                default="simple",
                max_length=20,
            ),
        ),
    ]
