# Generated by Django 5.2 on 2025-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_acces_profile_access_alter_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="niveau",
        ),
    ]
